module AhuInstructions exposing (ahuinstructions)


ahuinstructions : String
ahuinstructions =
    """

# Building Circulation

The circulation diagram shows an animation of the cooling system of a building.
The circle represents a pie chart of the air going in and out of the building
(in reality the airflow is continuous, not cyclical of course.) The air is
cooled as it passes through the cooling system (coil), warmed as it passes
through the building, and then exits the building. Note that a portion of the
outflowing air is redirected back into the building (Outside Air %).

## Outside Air

You can adjust the Outside Air Drybulb Temperature, Outside Air Wetbulb
Temperature, and Outside Air %.

The outside air temperature is the reading of an outdoor thermometer in the shade.

The outside air wet bulb temperature is a measure of the humidity outdoors.

It is usually unnecessary to use 100% outside air as input into the building.
Instead, it is more energy efficient to recirculate a percentage of the outgoing
air back into the cooling system. A minimum of 20% outside air is required for
fresh air in the building.
# Psychrometric Chart

The rest of the simulation is a representation of a [Psychrometric
Chart](https://en.wikipedia.org/wiki/Psychrometrics#Psychrometric_charts). The
horizontal axis is the dry bulb temperature; the vertical axis is the humidity
ratio.

## Set Load...

Cooling Load is the amount of energy required to cool the building, and includes
the heat generated by the building (by people, machines, computers), the
conductive and radiative heat entering the building (through walls, windows,
etc.), and the energy required to remove humidity from the air.

Sensible Heat Factor is the proportion of the cooling load that is "sensible"
heat (lowering temperature, vs removing moisture). A low sensible heat factor
means most energy is spent removing moisture from the air (think indoor pool,
sauna, greenhouse). A high sensible heat factor means that there is little or no
moisture to remove from the air (a computer data center, for instance).

## ...adjust Supply Air to maintain comfort.

The supply air is the air coming out of the building's cooling system. You
control the system by adjusting the temperature of the supply air temperature,
and the flow rate of the supply air.

Note: The Supply Air Temperature is the *output* of the cooling system, and the
Cooling Load is defined to include all energy required to cool the building.
Therefore, adjusting the Outside Air temperature and humidity will not affect
the building's temperature or humidity. (It may affect the system's
energy-efficiency, but that is not the purpose of this simulation.)


"""
